### ISSUE TITLE
[All] Shotgun Double-taps primary target

### ISSUE THREAD

**Issue by dave-sWpR46Ae** [ArcanePariah/Night-of-the-Dead#37]
Shotgun does regular damage and 100% splash damage to the primary target, effectively doing double damage.  Other weapons do not seem to do this, other than the flamethrower which might also do this, but the damage is so small, and the spread is so unique, I don't think it is worth fixing if it does indeed happen as well.

**Comment by ReduxGelum** [comment]
Squish and I brainstormed about making sg single tap, display the new number in gun description, and change the splash values (cos splash doesnt 2x hit), in the end I only added a short text to gun description. Other weapons used to do this too, and were changed like laser does 26 damage instead of 13 now, but nobody ever touched sg for some reason.

**Comment by dave-sWpR46Ae** [comment]
IMO SG needs a nerf.  I would not increase the single target damage or reduce splash damage at all, just make it like every other gun

**Comment by ReduxGelum** [comment]
Nerfing sg is too big of a change, I don't think its a good idea to touch its balance. Like OP flamer, its just too intertwined with existing skills and bosses. If possible I would be for some kind of rework that explains it better to player, that's about it.

**Comment by dave-sWpR46Ae** [comment]
WONTFIX
